language: python
sudo: required
dist: xenial
python:
  - '3.7'
env:
  - DJANGO_VERSION=">=1.11.17,<2.0"
  - DJANGO_VERSION=">=2.2"
install:
  - pip install -r tests/requirements.txt
  - pip install -U django$DJANGO_VERSION
script:
  - python manage.py test
