language: python
sudo: required
dist: xenial
python:
  - '3.10'
env:
  - DJANGO_VERSION=">=2.2.0,<2.3"
  - DJANGO_VERSION=">=3.0.0,<3.2.8"
install:
  - pip install -r tests/requirements.txt
  - pip install -U django$DJANGO_VERSION
script:
  - python manage.py test
