name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        django: ["3.2", "4.0", "4.1", "4.2"]
        exclude:
          - python: "3.11"
            django: "3.2"
          - python: "3.11"
            django: "4.0"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: pip install -r tests/requirements.txt
    - name: Install dependencies
      run: pip install -U django==${{ matrix.django }}
    - name: Run tests
      run: python manage.py test
