name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python: ["3.11", "3.12"]
        django: ["4.2", "5.0", "5.1", "5.2"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: pip install -r tests/requirements.txt
    - name: Install dependencies
      run: pip install -U django==${{ matrix.django }}
    - name: Run tests
      run: python manage.py test
